// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ToastContainer } from 'react-toastify';
// import Sidebar from "./master-admin/sidebar";
// import Menu from "./menu"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body 
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* <Sidebar/> */}
//         {/* <Menu/>
//         {children} */}
//           {/* <div style={{ display: 'flex' }}>
//             <Menu />
//             <div style={{ flex: 1, padding: '20px' }}> */}
//                 {children}
//             {/* </div>
//         </div> */}
        
//         <ToastContainer position="top-center" autoClose={2000} hideProgressBar newestOnTop closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover />
//       </body>
//     </html>
//   );
// }




"use client";
import { usePathname } from "next/navigation";
import Sidebar from "./navbar/page"; // Import navbar
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import "./graphstyles.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // Show navbar only if NOT on the login page
  const showNavbar = pathname !== "/";

  return (
    // <div className="flex">
    //   {showNavbar && <Sidebar />}  {/* Display navbar globally except on login page */}
    //   <main className="flex-grow">{children}</main>
    // </div>

    <html lang="en">
      <body>
        <div className="flex">
          {showNavbar && <Sidebar />}  {/* Display navbar globally except on login page */}
          <main className="flex-grow">{children}</main>
        </div>
        {/* {children} */}
        <ToastContainer position="top-center" autoClose={1000} hideProgressBar newestOnTop closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover />
      </body>
    </html>
  );
}
